# Generated by Django 4.0.2 on 2022-02-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
